web:
  image: nginx
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  ports:
    - "80:80"
  links:
    - botapi1
    - botapi2
    - botapi3

app:
  image: 288612536250.dkr.ecr.us-west-2.amazonaws.com/botapi:latest
  environment:
    PORT: 80
    REDISTOGO_URL: "redis://redistogo:c06aa5b0593da65715c0547940370ff9@tarpon.redistogo.com:9769/"

botapi1:
  extends: app

botapi2:
  extends: app

botapi3:
  extends: app
