version: "2"
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      STEAM_NAME: ""
      STEAM_USER: ""
      STEAM_PASS: ""
      # Can we inject this at runtime, rather than baking it in?
      STEAM_GUARD: ""
      REDISTOGO_URL: "redis://redis:6379/0"
      PORT: 5000
  redis:
    image: redis
